### Step 1: Import the necessary libraries

In [ ]:
import pandas as pd
from google.colab import files

In [ ]:
!unzip -q archive.zip
!ls

archive.zip  heart.csv	sample_data

In [ ]:
!ls

archive.zip  heart.csv	sample_data

In [ ]:
import io

heart_df = pd.read_csv('heart.csv')

In [ ]:
# print out the dataframe to have a look
heart_df.head(10)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
5,39,M,NAP,120,339,0,Normal,170,N,0.0,Up,0
6,45,F,ATA,130,237,0,Normal,170,N,0.0,Up,0
7,54,M,ATA,110,208,0,Normal,142,N,0.0,Up,0
8,37,M,ASY,140,207,0,Normal,130,Y,1.5,Flat,1
9,48,F,ATA,120,284,0,Normal,120,N,0.0,Up,0

In [ ]:
duplicated_rows = heart_df[heart_df.duplicated()]
print(duplicated_rows)

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease]
Index: []

Check for data types

In [ ]:
heart_df.dtypes

Age                 int64
Sex                object
ChestPainType      object
RestingBP           int64
Cholesterol         int64
FastingBS           int64
RestingECG         object
MaxHR               int64
ExerciseAngina     object
Oldpeak           float64
ST_Slope           object
HeartDisease        int64
dtype: object

In [ ]:
num_vars = heart_df.columns[heart_df.dtypes != "object"]
cat_vars = heart_df.columns[heart_df.dtypes == "object"]

print("num vars are: ", num_vars)
print("cat vars are: ", cat_vars)

num vars are:  Index(['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak',
       'HeartDisease'],
      dtype='object')
cat vars are:  Index(['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope'], dtype='object')

In [ ]:
heart_df[num_vars]

     Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak  HeartDisease
0     40        140          289          0    172      0.0             0
1     49        160          180          0    156      1.0             1
2     37        130          283          0     98      0.0             0
3     48        138          214          0    108      1.5             1
4     54        150          195          0    122      0.0             0
..   ...        ...          ...        ...    ...      ...           ...
913   45        110          264          0    132      1.2             1
914   68        144          193          1    141      3.4             1
915   57        130          131          0    115      1.2             1
916   57        130          236          0    174      0.0             1
917   38        138          175          0    173      0.0             0

[918 rows x 7 columns]

In [ ]:
heart_df[num_vars].isnull()

       Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak  HeartDisease
0    False      False        False      False  False    False         False
1    False      False        False      False  False    False         False
2    False      False        False      False  False    False         False
3    False      False        False      False  False    False         False
4    False      False        False      False  False    False         False
..     ...        ...          ...        ...    ...      ...           ...
913  False      False        False      False  False    False         False
914  False      False        False      False  False    False         False
915  False      False        False      False  False    False         False
916  False      False        False      False  False    False         False
917  False      False        False      False  False    False         False

[918 rows x 7 columns]

In [ ]:
heart_df[num_vars].isnull().sum()

Age             0
RestingBP       0
Cholesterol     0
FastingBS       0
MaxHR           0
Oldpeak         0
HeartDisease    0
dtype: int64

In [ ]:
heart_df[cat_vars].isnull().sum()

Sex               0
ChestPainType     0
RestingECG        0
ExerciseAngina    0
ST_Slope          0
dtype: int64

In [ ]:
heart_df.to_csv('cleaned_heart.csv', index=False)